# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CicekSepetiCase' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CicekSepetiCase

pod 'PromiseKit/Alamofire', '~> 6.0'
pod 'AlamofireImage', '~> 3.5'

end
